# MsSQL 
# Install the MySQL driver:
#   gem install mysql
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native architecture
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#
# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
#development:
#  adapter: mysql
#  encoding: utf8
#  database: proman_development
#  username: proman2
#  password: eg-353-projects
#  host: localhost

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
#test:
#  adapter: mysql
#  encoding: utf8
#  database: proman_test
#  username: proman2
#  password: eg-353-projects
#  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: proman_production
  username: proman2
  password: eg-353-projects
  host: localhost